apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bootcounter
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /counter
        backend:
          serviceName: bootcounter
          servicePort: 7070